# Generated by Django 5.0.6 on 2026-01-25 14:09

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Project',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('type', models.CharField(choices=[('portfolio', 'Portfolio'), ('gallery', 'Gallery')], max_length=20)),
                ('main_metrics', models.CharField(max_length=255)),
                ('platform', models.CharField(blank=True, choices=[('Facebook', 'Facebook'), ('Google', 'Google'), ('TikTok', 'TikTok'), ('LinkedIn', 'LinkedIn'), ('YouTube', 'YouTube'), ('Analytics', 'Analytics'), ('Other', 'Other')], max_length=50)),
                ('details', models.TextField()),
                ('hero_image', models.ImageField(upload_to='projects/hero/')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='ProjectImage',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='projects/gallery/')),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='images', to='app.project')),
            ],
        ),
    ]
