# Generated by Django 5.0.6 on 2026-01-25 14:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0002_project_bg_project_description_project_slug'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='project',
            name='main_metrics',
        ),
    ]
