# Generated by Django 6.0.1 on 2026-01-27 04:08

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0003_remove_project_main_metrics'),
    ]

    operations = [
        migrations.CreateModel(
            name='ProjectGallery',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('slug', models.SlugField(unique=True)),
                ('description', models.CharField(blank=True, max_length=255)),
                ('bg', models.CharField(default='from-blue-50 to-indigo-100', max_length=100)),
                ('platform', models.CharField(blank=True, choices=[('Facebook', 'Facebook'), ('Google', 'Google'), ('TikTok', 'TikTok'), ('LinkedIn', 'LinkedIn'), ('YouTube', 'YouTube'), ('Analytics', 'Analytics'), ('Other', 'Other')], max_length=50)),
                ('details', models.TextField()),
                ('hero_image', models.ImageField(upload_to='projects/gallery/hero/')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='ProjectPortfolio',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('slug', models.SlugField(unique=True)),
                ('description', models.CharField(blank=True, max_length=255)),
                ('bg', models.CharField(default='from-blue-50 to-indigo-100', max_length=100)),
                ('platform', models.CharField(blank=True, choices=[('Facebook', 'Facebook'), ('Google', 'Google'), ('TikTok', 'TikTok'), ('LinkedIn', 'LinkedIn'), ('YouTube', 'YouTube'), ('Analytics', 'Analytics'), ('Other', 'Other')], max_length=50)),
                ('details', models.TextField()),
                ('hero_image', models.ImageField(upload_to='projects/portfolio/hero/')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.RemoveField(
            model_name='projectimage',
            name='project',
        ),
        migrations.CreateModel(
            name='GalleryImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='projects/gallery/images/')),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='images', to='app.projectgallery')),
            ],
        ),
        migrations.CreateModel(
            name='PortfolioImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='projects/portfolio/gallery/')),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='images', to='app.projectportfolio')),
            ],
        ),
        migrations.DeleteModel(
            name='Project',
        ),
        migrations.DeleteModel(
            name='ProjectImage',
        ),
    ]
