# Generated by Django 6.0.1 on 2026-01-27 05:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0004_projectgallery_projectportfolio_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Stat',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100)),
                ('value', models.CharField(max_length=50)),
                ('color_bg', models.CharField(default='bg-purple-100', max_length=50)),
                ('color_text', models.CharField(default='text-purple-600', max_length=50)),
            ],
        ),
    ]
